yarray: []
mpaginate: 3
author: 'Rafael Picanço'
url: https://portfolio.rafael.picanco.nom.br
exclude: ['.gitignore',
          'CNAME',
          'portfolio.sublime-project',
          'portfolio.sublime-workspace',
          'Gemfile',
          'Gemfile.lock',
          'Gruntfile.js',
          'LICENSE.md',
          'README.md',
          'package.json',
          'css/min/',
          'js/src/',
          'node_modules/',
          'python/',
          'vendor',
          'tests.html',
          'nodejs',
          'workflow'
          ]
defaults:
  -
    scope:
      path: ''
    values:
      author: 'Rafael Picanço'
  -
    scope:
      path: 'pt-br'
    values:
      language: pt-BR
  -
    scope:
      path: 'en'
    values:
      language: en

plugins:
  - jemoji

sass:
    sass_dir: _sass
    style: compressed
    sourcemap: never

assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"