category: intro
en:
  title: How can I help you?
  credential: Behavioral Scientist
  content: >
    I have a degree in Psychology (2010),
    a master's degree (2013) and a doctor's degree (2018) in Psychology (Theory and Behavioral Research),
    all received from the Universidade Federal do Pará (Brazil).
    My expertise is Experimental Analysis of Behavior.
    I have worked in the following topics:
    basic learning processes,
    discriminative processes, verbal behavior and computer vision.
    I have strong interests in educational systems based on
    active methodologies, self-management and translational research in the field of individualized teaching.

pt-BR:
  title: Como posso ajudar você?
  credential: Cientista do Comportamento
  content: >
    Possuo graduação em Psicologia (2010),
    mestrado (2013) e doutorado (2018) em Psicologia (Teoria e Pesquisa do Comportamento),
    todos pela Universidade Federal do Pará.
    Minha especialidade é Análise Experimental do Comportamento.
    Tenho atuado principalmente nos seguintes temas:
    processos básicos de aprendizagem,
    processos discriminativos, comportamento verbal e visão computacional.    
    Possuo forte interesse em sistemas educacionais pautados
    em metodologias ativas, autogerenciamento e pesquisa translacional no campo do ensino individualizado.